image:
  repository: mongo
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 27017

replicas: 1

persistence:
  enabled: true
  storageClass: ""
  accessModes:
    - ReadWriteOnce
  size: 1Gi

