apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-green
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: frontend-green
  template:
    metadata:
      labels:
        app: frontend-green
    spec:
      containers:
        - name: frontend-green
          image: "{{ .Values.image.repository }}:{{ .Values.image.greenTag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          ports:
            - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-blue
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: frontend-blue
  template:
    metadata:
      labels:
        app: frontend-blue
    spec:
      containers:
        - name: frontend-blue
          image: "{{ .Values.image.repository }}:{{ .Values.image.blueTag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          ports:
            - containerPort: 80

