apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ .Values.destinationRule.name }}
spec:
  host: {{ .Values.destinationRule.host }}
  subsets:
    {{- range .Values.destinationRule.subsets }}
    - name: {{ .name }}
      labels:
        {{- toYaml .labels | nindent 8 }}
    {{- end }}

