apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ .Values.gateway.name }}
spec:
  selector:
    {{- toYaml .Values.gateway.selector | nindent 4 }}
  servers:
    - port:
        number: {{ .Values.gateway.port.number }}
        name: {{ .Values.gateway.port.name }}
        protocol: {{ .Values.gateway.port.protocol }}
      hosts:
        {{- range .Values.gateway.hosts }}
        - {{ . }}
        {{- end }}
